version: '3'

networks:
  cvfwdnetwork:
    driver: bridge

services:
  mysqldatabase:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=cvdb
      - MYSQL_ONETIME_PASSWORD=true
    networks:
      - cvfwdnetwork

  bookfwd:
    build: ""
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldatabase/cvdb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=test123
    depends_on:
      - mysqldatabase
    networks:
      - cvfwdnetwork